# https://taskfile.org

version: '2'

vars:
  EXE: algoc

tasks:
  build:
    cmds:
      - go build -o {{.EXE}}

  run:
    cmds:
      - ./{{.EXE}}
    silent: true

  clean:
    cmds:
      - rm {{.EXE}}
